/* AUTO-GENERATED by tools/sync_mech_to_elec.py — 勿手改，改 CSV 后重跑脚本 */
#ifndef PARAMS_FROM_MECH_H
#define PARAMS_FROM_MECH_H

#define MECH_Ks 200.0  /* 联轴器扭转刚度 [N*m/rad] 柔性联轴器选型定案（双惯量弹性环节刚度） */
#define MECH_J1 0.002  /* 电机侧等效惯量 [kg*m2] 含转子+编码器+小齿轮折算到电机轴 */
#define MECH_J2 0.02  /* 负载侧等效惯量 [kg*m2] 末端执行器折算到电机轴 */
#define MECH_B 0.01  /* 粘性阻尼系数 [N*m*s/rad] 轴承+密封+齿轮啮合等效 */
#define MECH_i 1.0  /* 传动比 [] 负载已折算到电机轴则填1；否则填减速比 */
#define MECH_wr 120.0  /* 额定转速 [rad/s] 仿真基准转速（≈1146 rpm） */
#define MECH_WN 331.6625  /* 双惯量无阻尼固有频率 rad/s */

#endif
