#!/usr/bin/env python3
# tools/sync_mech_to_elec.py
# 跨组「唯一数据源」同步脚本。
# 机械组只在 data/shared/mech_deliverables.csv 填一次参数；
# 电控组跑本脚本，机械交付参数就「直接跳出来」——自动生成 C 头文件 + JSON，无需重复手填。
# 用法：python tools/sync_mech_to_elec.py
import csv, json, math, os, sys

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
CSV_PATH = os.path.join(ROOT, "data", "shared", "mech_deliverables.csv")
H_OUT = os.path.join(ROOT, "electrical", "src", "params_from_mech.h")
JSON_OUT = os.path.join(ROOT, "data", "shared", "mech_deliverables_resolved.json")


def main():
    if not os.path.exists(CSV_PATH):
        print(f"[ERR] 找不到 {CSV_PATH}，请机械组先填写该 CSV", file=sys.stderr)
        return 1
    rows = []
    with open(CSV_PATH, newline="", encoding="utf-8-sig") as f:
        for r in csv.DictReader(f):
            if not r.get("symbol"):
                continue
            try:
                r["_v"] = float(r["value"]) if r["value"] not in ("", None) else None
            except ValueError:
                r["_v"] = None
            rows.append(r)
    d = {r["symbol"]: r for r in rows}

    def get(sym):
        return d[sym]["_v"] if sym in d else None

    Ks, J1, J2 = get("Ks"), get("J1"), get("J2")
    wn = None
    if None not in (Ks, J1, J2) and (J1 + J2) != 0:
        wn = math.sqrt(Ks * (1.0 / J1 + 1.0 / J2))

    os.makedirs(os.path.dirname(H_OUT), exist_ok=True)
    lines = ["/* AUTO-GENERATED by tools/sync_mech_to_elec.py — 勿手改，改 CSV 后重跑脚本 */",
             "#ifndef PARAMS_FROM_MECH_H", "#define PARAMS_FROM_MECH_H", ""]
    for r in rows:
        if r["_v"] is not None:
            lines.append(f"#define MECH_{r['symbol']} {r['_v']}  /* {r['param']} [{r['unit']}] {r['note']} */")
    if wn is not None:
        lines.append(f"#define MECH_WN {wn:.4f}  /* 双惯量无阻尼固有频率 rad/s */")
    lines += ["", "#endif", ""]
    with open(H_OUT, "w", encoding="utf-8") as f:
        f.write("\n".join(lines))

    out = {"params": [{k: r[k] for k in ("param", "symbol", "value", "unit", "week", "note")} for r in rows],
           "derived": {"wn_rad_s": round(wn, 4) if wn is not None else None}}
    with open(JSON_OUT, "w", encoding="utf-8") as f:
        json.dump(out, f, ensure_ascii=False, indent=2)

    print("=== 机械组交付参数（电控组直接读取，请勿在电控侧重复手填）===")
    for r in rows:
        print(f"  {r['symbol']:>6} = {r['value']:>8} {r['unit']:<10} | {r['param']}  ({r['week']})")
    if wn is not None:
        print(f"  >> 双惯量固有频率 ω_n = {wn:.3f} rad/s  ({wn / 2 / math.pi:.2f} Hz)")
        print(f"  >> 带宽-刚度匹配准则：观测器/陷波带宽应覆盖 ω_n 的 2~5 倍 ≈ {2 * wn:.0f}~{5 * wn:.0f} rad/s")
    print(f"\n已生成：\n  {H_OUT}\n  {JSON_OUT}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
