#!/usr/bin/env python3
# tools/sync_mech_to_elec.py
# 跨组「唯一数据源」同步脚本 —— 机械组只在一个地方手写参数。
#
# 设计目标（本科生零困惑）：
#   机械组只在 data/shared/mech_deliverables.csv 填一次参数；
#   跑本脚本 = 一次做完三件事：
#     ① 生成 electrical/src/params_from_mech.h      （电控组代码可直接 #include 读取）
#     ② 写回 data/mechanical/mech_params.json        （代码真正读取的源）
#     ③ 自动调用 electrical/c/merge_params.py        （再生成 data/params.json + build/params_generated.h，喂给 C/Python/MATLAB 仿真）
#   电控组无需再手填任何机械参数：git pull 后重编即可。
#
# 用法：python tools/sync_mech_to_elec.py
import csv, json, math, os, sys, subprocess

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
CSV_PATH = os.path.join(ROOT, "data", "shared", "mech_deliverables.csv")
H_OUT = os.path.join(ROOT, "electrical", "src", "params_from_mech.h")
JSON_OUT = os.path.join(ROOT, "data", "shared", "mech_deliverables_resolved.json")
MECH_JSON = os.path.join(ROOT, "data", "mechanical", "mech_params.json")
MERGE_SCRIPT = os.path.join(ROOT, "electrical", "c", "merge_params.py")


def main():
    if not os.path.exists(CSV_PATH):
        print(f"[ERR] 找不到 {CSV_PATH}，请机械组先填写该 CSV", file=sys.stderr)
        return 1
    rows = []
    with open(CSV_PATH, newline="", encoding="utf-8-sig") as f:
        for r in csv.DictReader(f):
            if not r.get("symbol"):
                continue
            try:
                r["_v"] = float(r["value"]) if r["value"] not in ("", None) else None
            except ValueError:
                r["_v"] = None
            rows.append(r)
    d = {r["symbol"]: r for r in rows}

    def get(sym):
        return d[sym]["_v"] if sym in d else None

    Ks, Ds, J1, J2, B, i = get("Ks"), get("Ds"), get("J1"), get("J2"), get("B"), get("i")
    wn = None
    if None not in (Ks, J1, J2) and (J1 + J2) != 0:
        wn = math.sqrt(Ks * (1.0 / J1 + 1.0 / J2))

    # -------------------------------------------------- ① 生成电控可直接 include 的头文件
    os.makedirs(os.path.dirname(H_OUT), exist_ok=True)
    lines = ["/* AUTO-GENERATED by tools/sync_mech_to_elec.py — 勿手改，改 CSV 后重跑脚本 */",
             "#ifndef PARAMS_FROM_MECH_H", "#define PARAMS_FROM_MECH_H", ""]
    for r in rows:
        if r["_v"] is not None:
            lines.append(f"#define MECH_{r['symbol']} {r['_v']}  /* {r['param']} [{r['unit']}] {r['note']} */")
    if wn is not None:
        lines.append(f"#define MECH_WN {wn:.4f}  /* 双惯量无阻尼固有频率 rad/s */")
    lines += ["", "#endif", ""]
    with open(H_OUT, "w", encoding="utf-8") as f:
        f.write("\n".join(lines))

    # -------------------------------------------------- ② 写回 mech_params.json（代码真正读的源）
    existing = {}
    if os.path.exists(MECH_JSON):
        try:
            with open(MECH_JSON, "r", encoding="utf-8") as f:
                existing = json.load(f)
        except json.JSONDecodeError:
            existing = {}
    meta = existing.get("meta", {})
    meta["version"] = meta.get("version", "v1")
    meta["note"] = "由 data/shared/mech_deliverables.csv 经 tools/sync_mech_to_elec.py 自动生成（CSV 为唯一手写入口，请勿手改本文件）"
    motor = existing.get("motor", {})
    if None not in (J1, B):
        motor["J"] = [J1, J1, J1, J1]          # 四台电机视为同型，统一取 J1
        motor["J_nominal"] = J1
        motor["B"] = [B, B, B, B]
    coupling = existing.get("coupling", {})
    if Ks is not None:
        coupling["Ks"] = Ks
    if Ds is not None:
        coupling["Ds"] = Ds
    if J1 is not None:
        coupling["J1"] = J1
    if J2 is not None:
        coupling["J2"] = J2
    if wn is not None:
        coupling["omega_n_rad_s"] = round(wn, 4)
    if i is not None:
        coupling["I_ratio"] = i
    out_json = {
        "meta": meta,
        "motor": motor,
        "coupling": coupling,
        "load_physics": existing.get("load_physics", {}),
    }
    os.makedirs(os.path.dirname(MECH_JSON), exist_ok=True)
    with open(MECH_JSON, "w", encoding="utf-8") as f:
        json.dump(out_json, f, ensure_ascii=False, indent=2)

    # -------------------------------------------------- ③ 自动跑 merge，生成仿真最终参数
    merge_ok = False
    if os.path.exists(MERGE_SCRIPT):
        try:
            r = subprocess.run([sys.executable, MERGE_SCRIPT],
                               capture_output=True, text=True, cwd=ROOT)
            sys.stdout.write(r.stdout)
            if r.returncode == 0:
                merge_ok = True
            else:
                sys.stderr.write(r.stderr)
                print("[WARN] merge_params.py 未成功（见上方报错），请修好 CSV/ctrl 参数后重跑本脚本。")
        except Exception as e:
            print(f"[WARN] 调用 merge_params.py 失败：{e}（头文件与 mech_params.json 已生成，可手动跑 merge）")
    else:
        print(f"[WARN] 找不到 {MERGE_SCRIPT}，跳过自动合并；请手动跑 merge_params.py。")

    # -------------------------------------------------- 衍生 JSON（ω_n 等留档）
    resolved = {"params": [{k: r[k] for k in ("param", "symbol", "value", "unit", "week", "note")} for r in rows],
                "derived": {"wn_rad_s": round(wn, 4) if wn is not None else None}}
    with open(JSON_OUT, "w", encoding="utf-8") as f:
        json.dump(resolved, f, ensure_ascii=False, indent=2)

    # -------------------------------------------------- 人看摘要
    print("=== 机械组交付参数（电控组直接读取，请勿在电控侧重复手填）===")
    for r in rows:
        print(f"  {r['symbol']:>6} = {r['value']:>8} {r['unit']:<10} | {r['param']}  ({r['week']})")
    if wn is not None:
        print(f"  >> 双惯量固有频率 ω_n = {wn:.3f} rad/s  ({wn / 2 / math.pi:.2f} Hz)")
        print(f"  >> 带宽-刚度匹配准则：观测器/陷波带宽应覆盖 ω_n 的 2~5 倍 ≈ {2 * wn:.0f}~{5 * wn:.0f} rad/s")
    print(f"\n已生成/更新：\n  {H_OUT}\n  {MECH_JSON}\n  {JSON_OUT}")
    if merge_ok:
        print(f"  自动合并成功 → data/params.json + build/params_generated.h（C/Python/MATLAB 仿真直接吃）")
    return 0


if __name__ == "__main__":
    sys.exit(main())
